### ISSUE TITLE
Token Authentication Error

### ISSUE THREAD

**Issue by adieball** [fragtastic/sentinelone-api-python#1]
Hi

when using the library I get some authentication errors:

`dieball@MBP14 sentinelone-api-python % /usr/bin/python3 /Users/adieball/Dropbox/Multiverse/Programming/python/sentinelone-api-python/getSites.py
Traceback (most recent call last):
  File "/Users/adieball/Dropbox/Multiverse/Programming/python/sentinelone-api-python/getSites.py", line 13, in <module>
    client.authenticate()
  File "/Users/adieball/Dropbox/Multiverse/Programming/python/sentinelone-api-python/sentineloneapi/client.py", line 31, in authenticate
    data, errors = self.LoginByApiToken()
  File "/Users/adieball/Dropbox/Multiverse/Programming/python/sentinelone-api-python/sentineloneapi/client.py", line 393, in LoginByApiToken
    return self.api_call(requests.post, endpoint, payload=payload)
  File "/Users/adieball/Dropbox/Multiverse/Programming/python/sentinelone-api-python/sentineloneapi/client.py", line 70, in api_call
    if isinstance(rj['data'], list):
KeyError: 'data'
adieball@MBP14 sentinelone-api-python % `

Looking into the code I see:

def _headers(self) -> Dict:
        if self._auth_token:
            return {
                'Authorization': f'Token {self._auth_token}',
                'Content-Type': 'application/json',

Shouldn't that be
 'Authorization': f'ApiToken {self._auth_token}',

?

**Comment by adieball** [comment]
fixed it on my own, was my mistake
